apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: marin3r
  name: marin3r-marin3r-envoyconfigrevision-editor-role
rules:
- apiGroups:
  - marin3r.3scale.net
  resources:
  - envoyconfigrevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marin3r.3scale.net
  resources:
  - envoyconfigrevisions/status
  verbs:
  - get
