apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: marin3r-kubebuilderv4-2
  name: marin3r-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: marin3r-controller-manager
  namespace: marin3r-system
