# Add the WATCH_NAMESPACE envvar
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: WATCH_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['olm.targetNamespaces']
# Expose the metrics endpoint on port 8080
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --metrics-bind-address=:8080
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
    - containerPort: 8080
      protocol: TCP
      name: metrics
