# This rule is not used by the project marin3r itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to operator.marin3r.3scale.net resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: marin3r
    app.kubernetes.io/managed-by: kustomize
  name: operator.marin3r-discoveryservice-viewer-role
rules:
- apiGroups:
  - operator.marin3r.3scale.net
  resources:
  - discoveryservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.marin3r.3scale.net
  resources:
  - discoveryservices/status
  verbs:
  - get
