# This rule is not used by the project marin3r itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the operator.marin3r.3scale.net.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: marin3r
    app.kubernetes.io/managed-by: kustomize
  name: operator.marin3r-envoydeployment-editor-role
rules:
- apiGroups:
  - operator.marin3r.3scale.net
  resources:
  - envoydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.marin3r.3scale.net
  resources:
  - envoydeployments/status
  verbs:
  - get
