name: catalog

on:
  push:
    branches:
    - main
    paths:
    - catalog/marin3r/stable-channel.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to quay.io/3scale
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & push catalog
        run: make catalog-publish CONTAINER_TOOL=docker
