name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Run tests
        run: |
          make test

      - name: Run e2e tests
        run: |
          make e2e-test CONTAINER_TOOL=docker
